//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPS_Helper.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SPS_Helper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Etc\ConnStr\.
        /// </summary>
        internal static string ConnectionStrings {
            get {
                return ResourceManager.GetString("ConnectionStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Core\MDX\.
        /// </summary>
        internal static string Core_MDX_Files_Subdir {
            get {
                return ResourceManager.GetString("Core_MDX_Files_Subdir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Core\Menu\.
        /// </summary>
        internal static string Core_Menu_Files_Subdir {
            get {
                return ResourceManager.GetString("Core_Menu_Files_Subdir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Core\PS\.
        /// </summary>
        internal static string Core_PS_Files_Subdir {
            get {
                return ResourceManager.GetString("Core_PS_Files_Subdir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Core\SQL\.
        /// </summary>
        internal static string Core_SQL_Files_Subdir {
            get {
                return ResourceManager.GetString("Core_SQL_Files_Subdir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на mdx,dax,xmla,dmx.
        /// </summary>
        internal static string List_mdx_ext {
            get {
                return ResourceManager.GetString("List_mdx_ext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на menu.
        /// </summary>
        internal static string List_menu_ext {
            get {
                return ResourceManager.GetString("List_menu_ext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ps,bat,com.
        /// </summary>
        internal static string List_ps_ext {
            get {
                return ResourceManager.GetString("List_ps_ext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на sql,txt.
        /// </summary>
        internal static string List_sql_ext {
            get {
                return ResourceManager.GetString("List_sql_ext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDX_Command {
            get {
                object obj = ResourceManager.GetObject("MDX_Command", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PS_Command {
            get {
                object obj = ResourceManager.GetObject("PS_command", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SQL_Command {
            get {
                object obj = ResourceManager.GetObject("SQL_Command", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scritps\ExtMenu\.
        /// </summary>
        internal static string Work_Menu_Files_Subdir {
            get {
                return ResourceManager.GetString("Work_Menu_Files_Subdir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scritps\Powershell\.
        /// </summary>
        internal static string Work_PS_Files_Subdir {
            get {
                return ResourceManager.GetString("Work_PS_Files_Subdir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scritps\SQL\.
        /// </summary>
        internal static string Work_SQL_Files_Subdir {
            get {
                return ResourceManager.GetString("Work_SQL_Files_Subdir", resourceCulture);
            }
        }
    }
}
